/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULT = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int LP = 12;
  /** RegularExpression Id. */
  int RP = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int RARROW = 15;
  /** RegularExpression Id. */
  int LARROW = 16;
  /** RegularExpression Id. */
  int SEMI = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int END = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int FOR = 23;
  /** RegularExpression Id. */
  int DOUBLEQUT = 24;
  /** RegularExpression Id. */
  int SINGLEQUT = 25;
  /** RegularExpression Id. */
  int CMP = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int FUNC = 30;
  /** RegularExpression Id. */
  int DEF = 31;
  /** RegularExpression Id. */
  int ID = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULT>",
    "<NUM>",
    "\"float\"",
    "\"int\"",
    "\"String\"",
    "\"char\"",
    "\"(\"",
    "\")\"",
    "<ASSIGN>",
    "\"->\"",
    "\"<-\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\"??\"",
    "\"!\"",
    "\"@\"",
    "\"&\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "<CMP>",
    "\"$\"",
    "\"|\"",
    "\"~\"",
    "\"func\"",
    "\"def\"",
    "<ID>",
    "\",\"",
  };

}
